### PR TITLE
[SGP-4203] Methods to close and open event RSVPs

### PR DESCRIPTION
**Pull request by jrfernandes**
[Close RSVPs documentation](https://www.meetup.com/meetup_api/docs/:urlname/events/:event_id/rsvps/close/)
[Open RSVPs documentation](https://www.meetup.com/meetup_api/docs/:urlname/events/:event_id/rsvps/open/)

### CODE REVIEW

**Comment by abendig** [comment]
Why did you not add mock tests here?

**Comment by jrfernandes** [comment]
There are already tests in place for the `invoke()` method: https://github.com/startupgrind/django-meetup/blob/142d8858b58906475cca80790ca93342b6afe2f8/meetup/tests/test_api.py#L66-L85

I can add a test that mocks `invoke()` to assert it's called with the expected URL, but, is that really helpful?

**Comment by abendig** [comment]
No. But in this case we're adding two new public methods. It would be helpful to add mock tests that assert that calling those will pass the correct information to invoke or post, no? 

The changes do look straightforward.

**Comment by jrfernandes** [comment]
Well, I [added these](https://github.com/startupgrind/django-meetup/pull/1/commits/9f00b8e9bc48e6e93b881a2b8b54aba832ca1ae1) just in case.

**Comment by abendig** [comment]
Thanks for adding those tests. They pass; all _our_ tests pass. Unfortunately, out of the box, there are five test failures. :(

```
(djangomeetup) Alexs-MacBook-Pro:django-meetup alex$ python setup.py test
running test
running egg_info
creating django_meetup.egg-info
writing requirements to django_meetup.egg-info/requires.txt
writing django_meetup.egg-info/PKG-INFO
writing top-level names to django_meetup.egg-info/top_level.txt
writing dependency_links to django_meetup.egg-info/dependency_links.txt
writing manifest file 'django_meetup.egg-info/SOURCES.txt'
reading manifest file 'django_meetup.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'django_meetup.egg-info/SOURCES.txt'
running build_ext
test_geo_stamp (meetup.tests.test_sync_utils.TestMeetupConversions) ... ERROR
test_parse_meetup_time (meetup.tests.test_sync_utils.TestMeetupConversions) ... ERROR
test_parse_meetup_time_tzinfo (meetup.tests.test_sync_utils.TestMeetupConversions) ... ERROR
test_to_meetup_timestamp (meetup.tests.test_sync_utils.TestMeetupConversions) ... ERROR
meetup.tests.test_models_sync (unittest.loader.ModuleImportFailure) ... ERROR
test_close_event_rsvps (meetup.tests.test_api.MeetupAPIEndpointsTests) ... ok
test_get_next_page_no_meta_is_none (meetup.tests.test_api.MeetupAPIEndpointsTests) ... ok
test_get_next_page_no_next_is_none (meetup.tests.test_api.MeetupAPIEndpointsTests) ... ok
test_get_next_page_uses_meta_to_fetch_next (meetup.tests.test_api.MeetupAPIEndpointsTests) ... ok
test_hit_rate_limit_waits (meetup.tests.test_api.MeetupAPIEndpointsTests) ... ok
test_invoke_delete_calls_requests (meetup.tests.test_api.MeetupAPIEndpointsTests) ... ok
test_invoke_get_calls_requests (meetup.tests.test_api.MeetupAPIEndpointsTests) ... ok
test_invoke_post_calls_requests (meetup.tests.test_api.MeetupAPIEndpointsTests) ... ok
test_open_event_rsvps (meetup.tests.test_api.MeetupAPIEndpointsTests) ... ok
test_get_next_page_no_meta_is_none (meetup.tests.test_api.MeetupClientTests) ... ok
test_get_next_page_no_next_is_none (meetup.tests.test_api.MeetupClientTests) ... ok
test_get_next_page_uses_meta_to_fetch_next (meetup.tests.test_api.MeetupClientTests) ... ok
test_hit_rate_limit_waits (meetup.tests.test_api.MeetupClientTests) ... ok
test_invoke_delete_calls_requests (meetup.tests.test_api.MeetupClientTests) ... ok
test_invoke_get_calls_requests (meetup.tests.test_api.MeetupClientTests) ... ok
test_invoke_post_calls_requests (meetup.tests.test_api.MeetupClientTests) ... ok

======================================================================
ERROR: test_geo_stamp (meetup.tests.test_sync_utils.TestMeetupConversions)
----------------------------------------------------------------------
TypeError: test_geo_stamp() takes no arguments (1 given)

======================================================================
ERROR: test_parse_meetup_time (meetup.tests.test_sync_utils.TestMeetupConversions)
----------------------------------------------------------------------
TypeError: test_parse_meetup_time() takes no arguments (1 given)

======================================================================
ERROR: test_parse_meetup_time_tzinfo (meetup.tests.test_sync_utils.TestMeetupConversions)
----------------------------------------------------------------------
TypeError: test_parse_meetup_time_tzinfo() takes no arguments (1 given)

======================================================================
ERROR: test_to_meetup_timestamp (meetup.tests.test_sync_utils.TestMeetupConversions)
----------------------------------------------------------------------
TypeError: test_to_meetup_timestamp() takes no arguments (1 given)

======================================================================
ERROR: meetup.tests.test_models_sync (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: meetup.tests.test_models_sync
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/alex/Development/django-meetup/meetup/tests/test_models_sync.py", line 14, in <module>
    from meetup.models import Event,Group,Venue,Member
  File "/Users/alex/Development/django-meetup/meetup/models.py", line 21, in <module>
    DEFAULT_VIEW_TIMEZONE = pytz.timezone(getattr(settings,"TIME_ZONE","UTC"))
  File "/Users/alex/Development/virtualenvs/djangomeetup/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/alex/Development/virtualenvs/djangomeetup/lib/python2.7/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
ImproperlyConfigured: Requested setting TIME_ZONE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.


----------------------------------------------------------------------
Ran 21 tests in 0.009s

FAILED (errors=5)
Test failed: <unittest.runner.TextTestResult run=21 errors=5 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=21 errors=5 failures=0>
```

I'm okay shipping this. We can address those separately, if necessary.

**Comment by jrfernandes** [comment]
That's unfortunate. I only tried the `test_api` suite, not the others. Honestly, it looks like the Meetup integration is going to stick around for a while, might be worth either starting our own lib or take over this one and updated.

Nonetheless, I would prefer to address those test issues separately (depending what the plan will be in regards to this library).

Going to ship.

**Pull request merged**
